Metrics/AbcSize:
  Enabled: false
AllCops:
  RunRailsCops: true
  Exclude:
    - '.*/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'manifests/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'