development:
  adapter: postgresql
  encoding: utf8
  # reconnect: false
  database: bug_tracker_dev
  pool: 5
  host: localhost
  username: postgres
  password: lol
  port: 5432
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock
test:
  adapter: postgresql
  encoding: utf8
  # reconnect: false
  database: bug_tracker_dev
  pool: 5
  username: postgres
  password: lol
  host: localhost
  port: 5432
       # socket: /Applications/MAMP/tmp/mysql/mysql.sock
production:
  adapter: postgresql
  host: localhost
  database:  bug_tracker_dev
  pool: 5


